In [1]:
import collect_data

dat = collect_data.df

dat.head(30)

,attacker_team,attacker_hero,victim_team,victim_hero,attacker_team_won,victim_role
0,Team 2,Mei,Team 1,Symmetra,True,Damage
1,Team 1,Baptiste,Team 1,Baptiste,False,Support
2,Team 2,Mei,Team 1,Mei,True,Damage
3,Team 2,Ramattra,Team 1,Ramattra,True,Tank
4,Team 2,Sojourn,Team 1,Mei,True,Damage
5,Team 1,Sojourn,Team 2,Sojourn,False,Damage
6,Team 2,Sojourn,Team 1,Symmetra,True,Damage
7,Team 1,Sojourn,Team 2,Ramattra,True,Tank
8,Team 1,Symmetra,Team 2,Lúcio,True,Support
9,Team 2,Sojourn,Team 1,Lúcio,True,Support
10,Team 2,Junkrat,Team 1,Baptiste,True,Support
11,Team 2,Junkrat,Team 1,Mei,False,Damage
12,Team 2,Junkrat,Team 1,Ramattra,True,Tank
0,Team 1,Winston,Team 2,Genji,True,Damage
1,Team 1,Tracer,Team 2,Brigitte,True,Support
2,Team 2,Genji,Team 1,Widowmaker,True,Damage
3,Team 1,Widowmaker,Team 2,Ashe,False,Damage
4,Team 2,Winston,Team 1,Genji,True,Damage
5,Team 2,Brigitte,Team 1,Winston,False,Tank
6,Team 2,Ashe,Team 1,Winston,True,Tank
7,Team 1,Genji,Team 2,Ana,True,Support
8,Team 2,Ashe,Team 1,Ana,True,Support
9,Team 1,Tracer,Team 2,Tracer,True,Damage
10,Team 2,Widowmaker,Team 1,Widowmaker,False,Damage
11,Team 1,Widowmaker,Team 2,Winston,True,Tank
12,Team 1,Widowmaker,Team 2,Widowmaker,True,Damage
13,Team 1,Tracer,Team 2,Sojourn,True,Damage
14,Team 2,Tracer,Team 1,Ana,True,Support
15,Team 2,Sojourn,Team 1,Echo,True,Damage
16,Team 1,Tracer,Team 2,Brigitte,False,Support